// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxI4Pwr85m1a1aCgddiKU_TNsfU9b9c-Q',
    appId: '1:725478574468:web:9ca3f0206005f69562f5d1',
    messagingSenderId: '725478574468',
    projectId: 'student-directory-app-1de79',
    authDomain: 'student-directory-app-1de79.firebaseapp.com',
    storageBucket: 'student-directory-app-1de79.firebasestorage.app',
    measurementId: 'G-46Y56JK76Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDhckXEoQyki6H2YrUp5N3Eh-3DA-q0I0',
    appId: '1:725478574468:android:d58fa314d5eb084962f5d1',
    messagingSenderId: '725478574468',
    projectId: 'student-directory-app-1de79',
    storageBucket: 'student-directory-app-1de79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TgBnLWxnYksv_RLHFo_A6LxkT-6XQoc',
    appId: '1:725478574468:ios:889cd94290b2d84e62f5d1',
    messagingSenderId: '725478574468',
    projectId: 'student-directory-app-1de79',
    storageBucket: 'student-directory-app-1de79.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_TgBnLWxnYksv_RLHFo_A6LxkT-6XQoc',
    appId: '1:725478574468:ios:889cd94290b2d84e62f5d1',
    messagingSenderId: '725478574468',
    projectId: 'student-directory-app-1de79',
    storageBucket: 'student-directory-app-1de79.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxI4Pwr85m1a1aCgddiKU_TNsfU9b9c-Q',
    appId: '1:725478574468:web:b6fa24d6e75fac9562f5d1',
    messagingSenderId: '725478574468',
    projectId: 'student-directory-app-1de79',
    authDomain: 'student-directory-app-1de79.firebaseapp.com',
    storageBucket: 'student-directory-app-1de79.firebasestorage.app',
    measurementId: 'G-6NC0X00BZR',
  );
}
